services:
  postgres:
    image: actuallyconnor/postgres:latest
    build:
      dockerfile: pgsql/Dockerfile
      context: .
      target: production
    expose:
      - 5432
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: evershop
      POSTGRES_PASSWORD: postgres
