name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      deployments: write
      contents: read

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/nakama/Dockerfile
          target: production
          push: true
          tags: |
            ghcr.io/ActuallyConnor/sentry:latest
            ghcr.io/ActuallyConnor/sentry:${{ github.sha }}
